Repository CeyLabs/Web3Ceylon-Web-FE, pull requests merged in 2025-09, with the labels that each got.

#19 feat: add assets to CountdownTicker and update CityEvent types
  public/assets/events/Colombo_GBG.png
  public/assets/events/Ella_GBG.png
  public/assets/events/Galle_GBG.png
  public/assets/events/Kandy_GBG.png
  src/components/CountdownTicker.tsx
  src/components/Header.tsx
  src/components/Hero.tsx
  src/components/Intro.tsx
  src/lib/events.ts
Labels: Review effort 2/5

#15 feat: add SiteLoader for interactive loading experience
  package.json
  public/Main-Logo.svg
  public/assets/events/Colombo_GBG.png
  public/assets/events/Ella_GBG.png
  public/assets/events/Galle_GBG.png
  public/assets/events/Kandy_GBG.png
  public/assets/logos/Colombo_Circle.png
  public/assets/logos/Ella_Circle.png
  public/assets/logos/Galle_Circle.png
  public/assets/logos/Kandy_Circle.png
  public/assets/logos/Main_Circle.png
  public/assets/stamps/Stamp - Colombo.png
  public/assets/stamps/Stamp - Ella.png
  public/assets/stamps/Stamp - Galle.png
  public/assets/stamps/Stamp - Kandy.png
  public/faq.webp
  src/app/api/volunteer/route.ts
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/metadata.ts
  src/app/page.tsx
  src/app/site-loader-provider.tsx
  src/components/CountdownTicker.tsx
  src/components/Header.tsx
  src/components/Hero.tsx
  src/components/Intro.tsx
  src/components/animations/ScrollReveal.tsx
  src/components/button/FixedContactButton.tsx
  src/components/form/ContactForm.tsx
  src/components/reusable/SiteLoader.tsx
  src/components/sections/AnimatedFAQ.tsx
  src/components/seo/JsonLd.tsx
  src/lib/events.ts
  src/lib/seo.ts
  src/styles/theme.css
  tailwind.config.ts
Labels: enhancement, Review effort 3/5

#22 revamp partners section
  public/assets/partners/ByBit_Black.png
  public/assets/partners/CeyCash_LongLight.png
  public/assets/partners/CeyLabs Long Black.png
  public/assets/partners/Metana-Logo.png
  public/assets/partners/founderflow-lk.png
  public/assets/partners/gdglk_cover.jpeg
  src/components/Partners.tsx
  src/components/reusable/Magnetic.tsx
Labels: Review effort 2/5

#25 feat: define standard font size scale
  README.md
  tailwind.config.ts
Labels: codex, Review effort 2/5

#24 refactor: replace custom text sizes with tokens
  src/components/sections/speakers.tsx
Labels: codex, Review effort 2/5

#26 refactor: replace custom heading text size in partners
  src/components/Partners.tsx
Labels: codex, Review effort 1/5

#30 feat: add colored social icons to footer links
  src/components/Footer.tsx
Labels: codex, Review effort 2/5

#36 Fix Kandy event type in FAQ
  src/components/sections/AnimatedFAQ.tsx
Labels: codex, Review effort 1/5

#37 feat: draggable auto-scrolling community partners carousel
  src/components/Partners.tsx
Labels: codex, Review effort 3/5

#27 refactor: use tailwind text size tokens in footer
  src/components/Footer.tsx
Labels: codex, Review effort 1/5

#34 Improve SEO metadata and OG tags
  public/og-image.png
  src/app/favicon.ico
  src/app/metadata.ts
  src/lib/seo.ts
Labels: codex, Review effort 2/5

#33 refactor: use typography tokens for cities section
  src/components/Cities.tsx
Labels: codex, Review effort 2/5

#43 feat: add knowledge and ecosystem partners
  public/assets/partners/Rotaract_Mora_Full_color.png
  public/assets/partners/gdglk_logo.png
  src/components/Partners.tsx
Labels: Review effort 2/5

#38 Add speaker social links on cards
  public/assets/speakers/Dilshan Abeygunawardana.webp
  public/assets/speakers/Dilshan Madusanka.webp
  public/assets/speakers/Diyath Sahan Rajapakshe.webp
  public/assets/speakers/Dumidu Thabrew.webp
  public/assets/speakers/Dumindu Kanishka.webp
  public/assets/speakers/Imeth Vinnath.webp
  public/assets/speakers/Kosala Jayasekara.webp
  public/assets/speakers/ManiyaWeb3.webp
  public/assets/speakers/Prabodha Lakshan.webp
  public/assets/speakers/Sanjeewa Silva.webp
  public/assets/speakers/Shaqeeq Khan.webp
  public/assets/speakers/Suresh Michael Peiris.webp
  src/components/Speakers.tsx
  src/components/sections/speakers.tsx
  src/data/speakerSet.ts
  src/data/speakers.ts
Labels: codex, Review effort 2/5

#45 feat: add new partner and speaker assets
  public/assets/partners/maash-logo.webp
  public/assets/speakers/Chirath Rajapaksha .webp
  public/assets/speakers/Kasum Asanka.webp
  public/assets/speakers/Niranga Indrajith Hettiarachchi.webp
  public/assets/speakers/Nissanka Seneviratne.webp
  src/components/Partners.tsx
  src/data/speakers.ts
Labels: Review effort 2/5

#46 feat: update Kandy speakers and Galle guest panel
  public/assets/speakers/Harsha Abegunasekara.webp
  src/data/speakers.ts
Labels: Review effort 2/5

#48 feat: update social hashtags and minor ui changes in create and share
  src/app/create-and-share/page.tsx
Labels: enhancement, Review effort 2/5
